dojo.provide("jazz.core.loader");dojo.declare("jazz.core.loader",null,{"-chains-":{constructor:"manual"}});dojo.provide("com.ibm.jdojo.lang.Runtime");
(function(){var d=jazz.core.loader;dojo.mixin(com.ibm.jdojo.lang.Runtime,{typeForName:function(a){var b=dojo.getObject(a);b||(d.load_sync(a),b=dojo.getObject(a));if(null==b)throw Error("Unknown type");return b},newInstance:function(a){var b=dojo.filter(arguments,function(c,a){return 0<a});return this.newInstanceWithArrayArgs(a,b)},newInstanceWithArrayArgs:function(a,b){function c(c){f.apply(this,c)}var f=null;if(dojo.isString(a))f=this.typeForName(a);else if(dojo.isFunction(a))f=a;else throw Error("type argument is expected to be a type name or constructor");
if(null==f)throw Error("Unknown type");c.prototype=f.prototype;return new c(b)},newInstanceByName:function(a,b){if(!dojo.isString(a))throw Error("type argument is expected to be a type name");var c=this,f=b,g=dojo.filter(arguments,function(c,a){return 1!=a});d.load_async(a,function(a){a=c.newInstance.apply(c,g);f(a)})},implementsInterface:function(a,b){if(!a)return!1;for(var c=a.constructor.prototype;c;){if(void 0!==c.$interfaces&&!0===c.$interfaces[b])return!0;c=c.constructor.superclass}return!1},
declareInterface:function(a,b){var c=dojo.declare(a,null,{constructor:function(){throw Error("Can't instantiate interface type");},$isInterface:!0});null!=b&&dojo.mixin(c,b);return c},isInstance:function(a,b){return b.prototype.$isInterface?this.implementsInterface(a,b.prototype.declaredClass):a instanceof b},getProperties:function(a){var b=[],c;for(c in a)b.push(c);return b},getValues:function(a){var b=[],c;for(c in a)b.push(a[c]);return b}})})();dojo.provide("com.ibm.team.chrome.common.Bootstrap");
(function(){var d=com.ibm.jdojo.lang.Runtime,a=dojo.declare("com.ibm.team.chrome.common.Bootstrap",null,{"-chains-":{constructor:"manual"}});a.content=function(a){window.setTimeout(function(){a.start()},0)};a.background=function(a){for(var c=d.getProperties(a),f=c.length,g=0;g<f;g++){var e=c[g],h=a[e];dojo.isFunction(h)&&(window[e]=dojo.hitch(a,h))}a.start()}})();dojo.provide("com.ibm.team.rtc.chrome.qls.CountryImages");
(function(){var d=dojo.declare("com.ibm.team.rtc.chrome.qls.CountryImages",null,{"-chains-":{constructor:"manual"}});d.CODES="AD AE AF AG AI AL AM AN AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET EU FI FJ FK FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GS GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW".split(" ");
d.getIconUrl=function(a,b){for(var c=[16,24,32,48,64],f=c[0],d=c.length,e=0;e<d;e++){var h=c[e];if(b<=h){f=h;break}}return"icons/country/"+f+"/"+a+".png"}})();dojo.provide("com.ibm.team.rtc.chrome.qls.Locales");
(function(){var d=com.ibm.team.rtc.chrome.qls.CountryImages,a=dojo.declare("com.ibm.team.rtc.chrome.qls.Locales",null,{"-chains-":{constructor:"manual"}});a.NULL={uuid:"$0",code:"",displayName:"Disabled",iconCode:"_unknown"};a.BUILT_IN=[a.NULL,{uuid:"$001",code:"en",displayName:"English",iconCode:"GB"},{uuid:"$002",code:"ar",displayName:"Arabic"},{uuid:"$003",code:"bg",displayName:"Bulgarian"},{uuid:"$004",code:"cs",displayName:"Czech",iconCode:"CZ"},{uuid:"$005",code:"da",displayName:"Danish",iconCode:"DK"},
{uuid:"$006",code:"de",displayName:"German"},{uuid:"$007",code:"el",displayName:"Greek",iconCode:"GR"},{uuid:"$008",code:"es",displayName:"Spanish"},{uuid:"$009",code:"fi",displayName:"Finnish"},{uuid:"$010",code:"fr",displayName:"French"},{uuid:"$011",code:"hr",displayName:"Croatian"},{uuid:"$012",code:"hu",displayName:"Hungarian"},{uuid:"$013",code:"it",displayName:"Italian"},{uuid:"$014",code:"ja",displayName:"Japanese",iconCode:"JP"},{uuid:"$015",code:"kk",displayName:"Kazakh",iconCode:"KZ"},
{uuid:"$016",code:"ko",displayName:"Korean",iconCode:"KR"},{uuid:"$017",code:"no",displayName:"Norwegian"},{uuid:"$018",code:"nl",displayName:"Dutch"},{uuid:"$019",code:"pl",displayName:"Polish"},{uuid:"$020",code:"pt",displayName:"Portugese (Portugal)"},{uuid:"$021",code:"pt-br",displayName:"Portugese (Brazil)",iconCode:"BR"},{uuid:"$022",code:"ro",displayName:"Romanian"},{uuid:"$023",code:"ru",displayName:"Russian"},{uuid:"$024",code:"sk",displayName:"Slovak"},{uuid:"$025",code:"sl",displayName:"Slovenian"},
{uuid:"$026",code:"sv",displayName:"Swedish"},{uuid:"$027",code:"th",displayName:"Thai"},{uuid:"$028",code:"tr",displayName:"Turkish"},{uuid:"$029",code:"uk",displayName:"Ukrainian",iconCode:"UA"},{uuid:"$030",code:"zh",displayName:"Chinese Simplified (ZH)",iconCode:"CN"},{uuid:"$031",code:"zh-tw",displayName:"Chinese Traditional",iconCode:"CN"},{uuid:"$032",code:"zh-cn",displayName:"Chinese Simplified (ZH-CN)",iconCode:"CN"}];a.DEFAULT=[a.BUILT_IN[0].uuid,a.BUILT_IN[1].uuid,a.BUILT_IN[6].uuid,a.BUILT_IN[19].uuid,
a.BUILT_IN[30].uuid];a.getIconUrl=function(a,c){return d.getIconUrl("undefined"!==typeof a.iconCode?a.iconCode:a.code.toUpperCase(),c)}})();dojo.provide("com.ibm.team.rtc.chrome.qls.BackgroundPage");
(function(){var d=com.ibm.team,a=d.chrome.common.Bootstrap,b=d.rtc.chrome.qls.Locales,d=dojo.declare("com.ibm.team.rtc.chrome.qls.BackgroundPage",null,{"-chains-":{constructor:"manual"},constructor:function(){},start:function(){chrome.storage.local.get("enabled-locales",dojo.hitch(this,function(a){a=a["enabled-locales"];null==a&&(a={enabled:this._getDefaultSetting()},chrome.storage.local.set({"enabled-locales":a}))}));chrome.webRequest.onBeforeSendHeaders.addListener(dojo.hitch(this,function(a){this._getLocale().uuid!==
b.NULL.uuid&&this._setHeader(a,"Accept-Language",this._getLocale().code);return{requestHeaders:a.requestHeaders}}),{urls:["<all_urls>"]},["blocking","requestHeaders"])},_setHeader:function(a,b,d){for(var e=a.requestHeaders,h=e.length,k=0;k<h;k++){var l=e[k];if(l.name===b){l.value=d;return}}a.requestHeaders.push({name:b,value:d})},getLocale:function(a){a(this._getLocale())},setLocale:function(a){window.localStorage.setItem("selected-locale",JSON.stringify(a));chrome.browserAction.setIcon({path:b.getIconUrl(a,
16)});chrome.tabs.reload(null,null)},_getLocale:function(){var a=window.localStorage.getItem("selected-locale");return null!=a?JSON.parse(a):b.NULL},_getDefaultSetting:function(){for(var a={},d=b.DEFAULT,g=d.length,e=0;e<g;e++)a[d[e]]=!0;return a},$interfaces:{"com.ibm.team.chrome.common.IEntry":!0,"com.ibm.team.rtc.chrome.qls.IBackgroundPage":!0}});d._=a.background(new d)})();
