dojo.provide("jazz.core.loader");dojo.declare("jazz.core.loader",null,{"-chains-":{constructor:"manual"}});dojo.provide("com.ibm.jdojo.lang.Runtime");
(function(){var a=jazz.core.loader;dojo.mixin(com.ibm.jdojo.lang.Runtime,{typeForName:function(c){var d=dojo.getObject(c);d||(a.load_sync(c),d=dojo.getObject(c));if(null==d)throw Error("Unknown type");return d},newInstance:function(c){var d=dojo.filter(arguments,function(c,d){return 0<d});return this.newInstanceWithArrayArgs(c,d)},newInstanceWithArrayArgs:function(c,d){function a(k){f.apply(this,k)}var f=null;if(dojo.isString(c))f=this.typeForName(c);else if(dojo.isFunction(c))f=c;else throw Error("type argument is expected to be a type name or constructor");
if(null==f)throw Error("Unknown type");a.prototype=f.prototype;return new a(d)},newInstanceByName:function(c,d){if(!dojo.isString(c))throw Error("type argument is expected to be a type name");var e=this,f=d,k=dojo.filter(arguments,function(k,b){return 1!=b});a.load_async(c,function(c){c=e.newInstance.apply(e,k);f(c)})},implementsInterface:function(c,d){if(!c)return!1;for(var a=c.constructor.prototype;a;){if(void 0!==a.$interfaces&&!0===a.$interfaces[d])return!0;a=a.constructor.superclass}return!1},
declareInterface:function(c,d){var a=dojo.declare(c,null,{constructor:function(){throw Error("Can't instantiate interface type");},$isInterface:!0});null!=d&&dojo.mixin(a,d);return a},isInstance:function(c,a){return a.prototype.$isInterface?this.implementsInterface(c,a.prototype.declaredClass):c instanceof a},getProperties:function(a){var d=[],e;for(e in a)d.push(e);return d},getValues:function(a){var d=[],e;for(e in a)d.push(a[e]);return d}})})();dojo.provide("com.ibm.team.chrome.common.Bootstrap");
(function(){var a=com.ibm.jdojo.lang.Runtime,c=dojo.declare("com.ibm.team.chrome.common.Bootstrap",null,{"-chains-":{constructor:"manual"}});c.content=function(a){window.setTimeout(function(){a.start()},0)};c.background=function(c){for(var e=a.getProperties(c),f=e.length,k=0;k<f;k++){var l=e[k],b=c[l];dojo.isFunction(b)&&(window[l]=dojo.hitch(c,b))}c.start()}})();dojo.provide("com.ibm.team.rtc.chrome.qls.CountryImages");
(function(){var a=dojo.declare("com.ibm.team.rtc.chrome.qls.CountryImages",null,{"-chains-":{constructor:"manual"}});a.CODES="AD AE AF AG AI AL AM AN AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET EU FI FJ FK FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GS GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW".split(" ");
a.getIconUrl=function(a,d){for(var e=[16,24,32,48,64],f=e[0],k=e.length,l=0;l<k;l++){var b=e[l];if(d<=b){f=b;break}}return"icons/country/"+f+"/"+a+".png"}})();dojo.provide("com.ibm.team.rtc.chrome.qls.Locales");
(function(){var a=com.ibm.team.rtc.chrome.qls.CountryImages,c=dojo.declare("com.ibm.team.rtc.chrome.qls.Locales",null,{"-chains-":{constructor:"manual"}});c.NULL={uuid:"$0",code:"",displayName:"Disabled",iconCode:"_unknown"};c.BUILT_IN=[c.NULL,{uuid:"$001",code:"en",displayName:"English",iconCode:"GB"},{uuid:"$002",code:"ar",displayName:"Arabic"},{uuid:"$003",code:"bg",displayName:"Bulgarian"},{uuid:"$004",code:"cs",displayName:"Czech",iconCode:"CZ"},{uuid:"$005",code:"da",displayName:"Danish",iconCode:"DK"},
{uuid:"$006",code:"de",displayName:"German"},{uuid:"$007",code:"el",displayName:"Greek",iconCode:"GR"},{uuid:"$008",code:"es",displayName:"Spanish"},{uuid:"$009",code:"fi",displayName:"Finnish"},{uuid:"$010",code:"fr",displayName:"French"},{uuid:"$011",code:"hr",displayName:"Croatian"},{uuid:"$012",code:"hu",displayName:"Hungarian"},{uuid:"$013",code:"it",displayName:"Italian"},{uuid:"$014",code:"ja",displayName:"Japanese",iconCode:"JP"},{uuid:"$015",code:"kk",displayName:"Kazakh",iconCode:"KZ"},
{uuid:"$016",code:"ko",displayName:"Korean",iconCode:"KR"},{uuid:"$017",code:"no",displayName:"Norwegian"},{uuid:"$018",code:"nl",displayName:"Dutch"},{uuid:"$019",code:"pl",displayName:"Polish"},{uuid:"$020",code:"pt",displayName:"Portugese (Portugal)"},{uuid:"$021",code:"pt-br",displayName:"Portugese (Brazil)",iconCode:"BR"},{uuid:"$022",code:"ro",displayName:"Romanian"},{uuid:"$023",code:"ru",displayName:"Russian"},{uuid:"$024",code:"sk",displayName:"Slovak"},{uuid:"$025",code:"sl",displayName:"Slovenian"},
{uuid:"$026",code:"sv",displayName:"Swedish"},{uuid:"$027",code:"th",displayName:"Thai"},{uuid:"$028",code:"tr",displayName:"Turkish"},{uuid:"$029",code:"uk",displayName:"Ukrainian",iconCode:"UA"},{uuid:"$030",code:"zh",displayName:"Chinese Simplified (ZH)",iconCode:"CN"},{uuid:"$031",code:"zh-tw",displayName:"Chinese Traditional",iconCode:"CN"},{uuid:"$032",code:"zh-cn",displayName:"Chinese Simplified (ZH-CN)",iconCode:"CN"}];c.DEFAULT=[c.BUILT_IN[0].uuid,c.BUILT_IN[1].uuid,c.BUILT_IN[6].uuid,c.BUILT_IN[19].uuid,
c.BUILT_IN[30].uuid];c.getIconUrl=function(c,e){return a.getIconUrl("undefined"!==typeof c.iconCode?c.iconCode:c.code.toUpperCase(),e)}})();dojo.provide("com.ibm.team.rtc.chrome.qls.UUID");(function(){var a=dojo.declare("com.ibm.team.rtc.chrome.qls.UUID",null,{"-chains-":{constructor:"manual"}});a.generate=function(){return a.s4()+a.s4()+"-"+a.s4()+"-"+a.s4()+"-"+a.s4()+"-"+a.s4()+a.s4()+a.s4()};a.s4=function(){return Math.floor(65536*(1+Math.random())).toString(16).substring(1)}})();dojo.provide("com.ibm.team.rtc.chrome.qls.options.Options");
(function(){var a=com.ibm.team,c=a.chrome.common.Bootstrap,a=a.rtc.chrome.qls,d=a.CountryImages,e=a.Locales,f=a.UUID,a=dojo.declare("com.ibm.team.rtc.chrome.qls.options.Options",null,{"-chains-":{constructor:"manual"},constructor:function(){},start:function(){this._renderLocales(e.BUILT_IN,!0);this._renderPicker();chrome.storage.local.get(["additional-locales","enabled-locales"],dojo.hitch(this,function(a){this._updateCustomLocales(a["additional-locales"]);this._updateEnablement(a["enabled-locales"])}));
chrome.storage.onChanged.addListener(dojo.hitch(this,function(a,c){var b=a["additional-locales"];null!=b&&this._updateCustomLocales(b.newValue);b=a["enabled-locales"];null!=b&&this._updateEnablement(b.newValue)}))},_renderLocales:function(a,c){for(var b=window.document,d=b.getElementById("locales-"+(c?"builtIn":"custom"));d.hasChildNodes();)d.removeChild(d.firstChild);for(var g=a.length,e=0;e<g;e++)d.appendChild(this._renderLocale(a[e],c));b.getElementById("add-locale-button").addEventListener("click",
dojo.hitch(this,function(a){a={uuid:f.generate(),code:b.getElementById("new-locale-code").value,displayName:b.getElementById("new-locale-displayname").value,iconCode:b.getElementById("new-locale-flag").value};this._toggleLocale(a,!0);b.getElementById("new-locale-flag").focus()}),!1)},_renderPicker:function(){for(var a=window.document,c=a.getElementById("new-locale-flag"),b=d.CODES,e=b.length,g=0;g<e;g++){var f=b[g],h=a.createElement("option");h.value=f;h.label=f;h.appendChild(a.createTextNode(f));
c.appendChild(h)}b=function(b){b=a.getElementById("flag-preview");var e=a.createElement("img");e.src=d.getIconUrl(c.value,16);null!=b.firstChild?b.replaceChild(e,b.firstChild):b.appendChild(e);b.appendChild(e)};b(null);c.addEventListener("change",b,!1)},_renderLocale:function(a,c){var b=window.document,d=b.createElement("tr"),g=b.createElement("td"),f=b.createElement("input");f.type="checkbox";f.name="locale-checkbox";f.setAttribute("data-locale-id",a.uuid);f.addEventListener("change",dojo.hitch(this,
function(b){this._toggleEnabled(a,f.checked)}),!1);d.appendChild(g);g.appendChild(f);var g=b.createElement("td"),h=b.createElement("img");h.src=e.getIconUrl(a,16);d.appendChild(g);g.appendChild(h);g=b.createElement("td");h=b.createElement("span");h.appendChild(b.createTextNode(a.code));d.appendChild(h);d.appendChild(g);g.appendChild(h);g=b.createElement("td");h=b.createElement("span");h.appendChild(b.createTextNode(a.displayName));d.appendChild(g);g.appendChild(h);g=b.createElement("td");d.appendChild(g);
c||(h=b.createElement("button"),h.className="btn btn-sm btn-danger",b=b.createElement("span"),b.className="glyphicon glyphicon-remove",b.title="Remove Locale",h.appendChild(b),g.appendChild(h),h.addEventListener("click",dojo.hitch(this,function(b){this._toggleLocale(a,!1)}),!1));return d},_updateCustomLocales:function(a){this._renderLocales(null!=a&&null!=a.locales?a.locales:[],!1)},_updateEnablement:function(a){var c=window.document.getElementsByName("locale-checkbox");a=a.enabled;for(var b=0;b<
c.length;b++){var d=c.item(b);d.checked=!!a[d.getAttribute("data-locale-id")]}},_toggleLocale:function(a,c){chrome.storage.local.get(["additional-locales","enabled-locales"],function(b){var d=b["additional-locales"];null==d&&(d={locales:[]});if(c)d.locales.push(a);else for(var e=0;e<d.locales.length;)d.locales[e].uuid===a.uuid?d.locales.splice(e,1):e++;b=b["enabled-locales"];c?b.enabled[a.uuid]=!0:delete b.enabled[a.uuid];chrome.storage.local.set({"additional-locales":d,"enabled-locales":b})})},_toggleEnabled:function(a,
c){chrome.storage.local.get(["enabled-locales"],function(b){b=b["enabled-locales"];c?b.enabled[a.uuid]=!0:delete b.enabled[a.uuid];chrome.storage.local.set({"enabled-locales":b})})},$interfaces:{"com.ibm.team.chrome.common.IEntry":!0}});a.DATA_LOCALE_ID="data-locale-id";a.LOCALE_CHECKBOX="locale-checkbox";a._=c.content(new a)})();
