dojo.provide("jazz.core.loader");dojo.declare("jazz.core.loader",null,{"-chains-":{constructor:"manual"}});dojo.provide("com.ibm.jdojo.lang.Runtime");
(function(){var d=jazz.core.loader;dojo.mixin(com.ibm.jdojo.lang.Runtime,{typeForName:function(a){var c=dojo.getObject(a);c||(d.load_sync(a),c=dojo.getObject(a));if(null==c)throw Error("Unknown type");return c},newInstance:function(a){var c=dojo.filter(arguments,function(a,c){return 0<c});return this.newInstanceWithArrayArgs(a,c)},newInstanceWithArrayArgs:function(a,c){function b(a){g.apply(this,a)}var g=null;if(dojo.isString(a))g=this.typeForName(a);else if(dojo.isFunction(a))g=a;else throw Error("type argument is expected to be a type name or constructor");
if(null==g)throw Error("Unknown type");b.prototype=g.prototype;return new b(c)},newInstanceByName:function(a,c){if(!dojo.isString(a))throw Error("type argument is expected to be a type name");var b=this,g=c,h=dojo.filter(arguments,function(a,c){return 1!=c});d.load_async(a,function(a){a=b.newInstance.apply(b,h);g(a)})},implementsInterface:function(a,c){if(!a)return!1;for(var b=a.constructor.prototype;b;){if(void 0!==b.$interfaces&&!0===b.$interfaces[c])return!0;b=b.constructor.superclass}return!1},
declareInterface:function(a,c){var b=dojo.declare(a,null,{constructor:function(){throw Error("Can't instantiate interface type");},$isInterface:!0});null!=c&&dojo.mixin(b,c);return b},isInstance:function(a,c){return c.prototype.$isInterface?this.implementsInterface(a,c.prototype.declaredClass):a instanceof c},getProperties:function(a){var c=[],b;for(b in a)c.push(b);return c},getValues:function(a){var c=[],b;for(b in a)c.push(a[b]);return c}})})();dojo.provide("com.ibm.team.chrome.common.Bootstrap");
(function(){var d=com.ibm.jdojo.lang.Runtime,a=dojo.declare("com.ibm.team.chrome.common.Bootstrap",null,{"-chains-":{constructor:"manual"}});a.content=function(a){window.setTimeout(function(){a.start()},0)};a.background=function(a){for(var b=d.getProperties(a),g=b.length,h=0;h<g;h++){var f=b[h],e=a[f];dojo.isFunction(e)&&(window[f]=dojo.hitch(a,e))}a.start()}})();dojo.provide("com.ibm.team.rtc.chrome.qls.CountryImages");
(function(){var d=dojo.declare("com.ibm.team.rtc.chrome.qls.CountryImages",null,{"-chains-":{constructor:"manual"}});d.CODES="AD AE AF AG AI AL AM AN AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BR BS BT BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET EU FI FJ FK FM FO FR GA GB GD GE GG GH GI GL GM GN GQ GR GS GT GU GW GY HK HN HR HT HU IC ID IE IL IM IN IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PN PR PS PT PW PY QA RO RS RU RW SA SB SC SD SE SG SH SI SK SL SM SN SO SR SS ST SV SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW".split(" ");
d.getIconUrl=function(a,c){for(var b=[16,24,32,48,64],g=b[0],h=b.length,f=0;f<h;f++){var e=b[f];if(c<=e){g=e;break}}return"icons/country/"+g+"/"+a+".png"}})();dojo.provide("com.ibm.team.rtc.chrome.qls.Locales");
(function(){var d=com.ibm.team.rtc.chrome.qls.CountryImages,a=dojo.declare("com.ibm.team.rtc.chrome.qls.Locales",null,{"-chains-":{constructor:"manual"}});a.NULL={uuid:"$0",code:"",displayName:"Disabled",iconCode:"_unknown"};a.BUILT_IN=[a.NULL,{uuid:"$001",code:"en",displayName:"English",iconCode:"GB"},{uuid:"$002",code:"ar",displayName:"Arabic"},{uuid:"$003",code:"bg",displayName:"Bulgarian"},{uuid:"$004",code:"cs",displayName:"Czech",iconCode:"CZ"},{uuid:"$005",code:"da",displayName:"Danish",iconCode:"DK"},
{uuid:"$006",code:"de",displayName:"German"},{uuid:"$007",code:"el",displayName:"Greek",iconCode:"GR"},{uuid:"$008",code:"es",displayName:"Spanish"},{uuid:"$009",code:"fi",displayName:"Finnish"},{uuid:"$010",code:"fr",displayName:"French"},{uuid:"$011",code:"hr",displayName:"Croatian"},{uuid:"$012",code:"hu",displayName:"Hungarian"},{uuid:"$013",code:"it",displayName:"Italian"},{uuid:"$014",code:"ja",displayName:"Japanese",iconCode:"JP"},{uuid:"$015",code:"kk",displayName:"Kazakh",iconCode:"KZ"},
{uuid:"$016",code:"ko",displayName:"Korean",iconCode:"KR"},{uuid:"$017",code:"no",displayName:"Norwegian"},{uuid:"$018",code:"nl",displayName:"Dutch"},{uuid:"$019",code:"pl",displayName:"Polish"},{uuid:"$020",code:"pt",displayName:"Portugese (Portugal)"},{uuid:"$021",code:"pt-br",displayName:"Portugese (Brazil)",iconCode:"BR"},{uuid:"$022",code:"ro",displayName:"Romanian"},{uuid:"$023",code:"ru",displayName:"Russian"},{uuid:"$024",code:"sk",displayName:"Slovak"},{uuid:"$025",code:"sl",displayName:"Slovenian"},
{uuid:"$026",code:"sv",displayName:"Swedish"},{uuid:"$027",code:"th",displayName:"Thai"},{uuid:"$028",code:"tr",displayName:"Turkish"},{uuid:"$029",code:"uk",displayName:"Ukrainian",iconCode:"UA"},{uuid:"$030",code:"zh",displayName:"Chinese Simplified (ZH)",iconCode:"CN"},{uuid:"$031",code:"zh-tw",displayName:"Chinese Traditional",iconCode:"CN"},{uuid:"$032",code:"zh-cn",displayName:"Chinese Simplified (ZH-CN)",iconCode:"CN"}];a.DEFAULT=[a.BUILT_IN[0].uuid,a.BUILT_IN[1].uuid,a.BUILT_IN[6].uuid,a.BUILT_IN[19].uuid,
a.BUILT_IN[30].uuid];a.getIconUrl=function(a,b){return d.getIconUrl("undefined"!==typeof a.iconCode?a.iconCode:a.code.toUpperCase(),b)}})();dojo.provide("com.ibm.team.rtc.chrome.qls.PopUp");
(function(){var d=com.ibm.team,a=d.chrome.common.Bootstrap,c=d.rtc.chrome.qls.Locales,b=dojo.declare("com.ibm.team.rtc.chrome.qls.PopUp",null,{"-chains-":{constructor:"manual"},constructor:function(){},start:function(){chrome.storage.local.get(["additional-locales","enabled-locales"],dojo.hitch(this,function(a){a=this._getAvailableLocales(a["enabled-locales"],a["additional-locales"]);this._list=this._renderLocales(a);window.document.body.appendChild(this._list);chrome.extension.getBackgroundPage().getLocale(dojo.hitch(this,
function(a){this._setSelected(a)}))}))},_renderLocales:function(a){a=a.sort(function(a,b){return a.uuid===c.NULL.uuid&&a!==b||b.uuid===c.NULL.uuid&&a!==b?-1:(null!=a?a.displayName:"").localeCompare(null!=b?b.displayName:"")});for(var b=dojo.create("ul",{className:"list-group"}),f=a.length,e=0;e<f;e++){var d=a[e];b.appendChild(this._renderEntry(d,d.displayName,c.getIconUrl(d,16)))}return b},_renderEntry:function(a,c,f){var e=dojo.create("li");dojo.attr(e,b.DATA_VALUE,null!=a?a.code:"");e.appendChild(dojo.create("img",
{src:f}));e.appendChild(dojo.doc.createTextNode(c));e.addEventListener("click",dojo.hitch(this,function(b){b=chrome.extension.getBackgroundPage();this._setSelected(a);b.setLocale(a)}),!1);return e},_getAvailableLocales:function(a,b){var f=[];Array.prototype.push.apply(f,c.BUILT_IN);null!=b&&null!=b.locales&&Array.prototype.push.apply(f,b.locales);for(var e=[],d=f.length,k=0;k<d;k++){var l=f[k];(null==a||null==a.enabled||l.uuid in a.enabled)&&e.push(l)}return e},_setSelected:function(a){for(var c=
0;c<this._list.childNodes.length;c++)dojo.removeAttr(this._list.childNodes.item(c),b.DATA_SELECTED);for(c=0;c<this._list.childNodes.length;c++){var d=this._list.childNodes.item(c);dojo.attr(d,b.DATA_VALUE)===a.code&&dojo.attr(d,b.DATA_SELECTED,"true")}},$interfaces:{"com.ibm.team.chrome.common.IEntry":!0}});b.DATA_SELECTED="data-selected";b.DATA_VALUE="data-value";b._=a.content(new b)})();
